services:
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data
    networks:
      - dev_network

  minio:
    image: minio/minio:latest
    environment:
      MINIO_SERVER_URL: http://localhost:${MINIO_PORT:-9000}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
    ports:
      - "${MINIO_PORT:-9000}:9000" # MinIO console and API
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - dev_network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI for email testing
    restart: unless-stopped
    networks:
      - dev_network

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - dev_network

networks:
  dev_network:

volumes:
  psql_volume_bp:
  minio_data:
  redis_data:
